logging.level.org.springframework.web: INFO
server.port: 8080

spring:

  h2.console:
    enabled: true
    path: /h2

  jpa.hibernate.ddl-auto: create-drop

  datasource:
    url: jdbc:h2:file:~/petstoremanager3;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver


